import { PrismaClient, CampaignChannel, CampaignStatus, CampaignType, ContactStatus, ExecutionMode, RecipientStatus, UserRole } from '@prisma/client';
import * as bcrypt from 'bcrypt';
const prisma = new PrismaClient();
async function main() {
  const passwordHash=await bcrypt.hash('Demo123!',12);
  const users=await Promise.all([['Administrador Demo','admin@conectamasivo.demo',UserRole.ADMIN],['Operador Demo','operador@conectamasivo.demo',UserRole.OPERATOR],['Consulta Demo','consulta@conectamasivo.demo',UserRole.VIEWER]].map(([name,email,role])=>prisma.user.upsert({where:{email:String(email)},update:{name:String(name),role:role as UserRole,passwordHash},create:{name:String(name),email:String(email),role:role as UserRole,passwordHash}})));
  const zones=['Zona 1','Zona 7','Zona 10','Quetzaltenango','Escuintla']; const groups=['Demo WhatsApp','Demo SMS','Comunidad Demo'];
  for(let index=1;index<=30;index++){const phone=`+502555${String(index).padStart(5,'0')}`;const whatsapp=index%3!==0, sms=index%4!==0, status=index===27?ContactStatus.BLOCKED:index===28?ContactStatus.INACTIVE:ContactStatus.ACTIVE; await prisma.contact.upsert({where:{phone},update:{},create:{firstName:`Demo${index}`,lastName:'Contacto',documentId:`DEMO-${String(index).padStart(3,'0')}`,phone,email:`demo.contacto${index}@example.invalid`,departmentOrZone:zones[index%zones.length],groupName:groups[index%groups.length],status,whatsappOptIn:whatsapp,smsOptIn:sms,consentSource:'Datos ficticios de demostración',consentAt:(whatsapp||sms)?new Date():null,isTwilioTestNumber:index<=3}});}
  const segment=await prisma.segment.upsert({where:{id:'00000000-0000-4000-8000-000000000001'},update:{},create:{id:'00000000-0000-4000-8000-000000000001',name:'Consentimiento WhatsApp activo',description:'Contactos activos con consentimiento WhatsApp',filters:{whatsappOptIn:true},isDynamic:true,createdById:users[0].id}});
  await prisma.segment.upsert({where:{id:'00000000-0000-4000-8000-000000000002'},update:{},create:{id:'00000000-0000-4000-8000-000000000002',name:'Números de prueba Twilio',description:'Solo números autorizados para Sandbox',filters:{isTwilioTestNumber:true},isDynamic:true,createdById:users[0].id}});
  const campaign=await prisma.campaign.upsert({where:{id:'00000000-0000-4000-8000-000000000010'},update:{},create:{id:'00000000-0000-4000-8000-000000000010',name:'Campaña demo de bienvenida',type:CampaignType.INFORMATIONAL,channel:CampaignChannel.WHATSAPP,executionMode:ExecutionMode.DEMO,status:CampaignStatus.COMPLETED,message:'Hola {{nombre}}, este es un mensaje simulado de Conecta Masivo.',segmentId:segment.id,createdById:users[0].id,estimatedRecipients:20,estimatedCost:0,sentAt:new Date()}});
  const contacts=await prisma.contact.findMany({where:{status:ContactStatus.ACTIVE,whatsappOptIn:true},take:10});
  for(const [index,contact] of contacts.entries()) await prisma.campaignRecipient.upsert({where:{campaignId_contactId_channel:{campaignId:campaign.id,contactId:contact.id,channel:CampaignChannel.WHATSAPP}},update:{},create:{campaignId:campaign.id,contactId:contact.id,channel:CampaignChannel.WHATSAPP,status:index===0?RecipientStatus.FAILED:index<7?RecipientStatus.READ:RecipientStatus.DELIVERED,renderedMessage:`Hola ${contact.firstName}, este es un mensaje simulado de Conecta Masivo.`,sentAt:index===0?null:new Date(),deliveredAt:index===0?null:new Date(),readAt:index>0&&index<7?new Date():null}});
  await prisma.appSetting.upsert({where:{id:'00000000-0000-4000-8000-000000000020'},update:{},create:{id:'00000000-0000-4000-8000-000000000020',organizationName:'Conecta Masivo Demo',supportEmail:'soporte@conectamasivo.demo',supportPhone:'+50255550000',allowedStartHour:8,allowedEndHour:20,whatsappUtilityRatePerThousand:25,whatsappMarketingRatePerThousand:40,smsRatePerThousand:15}});
}
main().then(()=>prisma.$disconnect()).catch(async error=>{console.error(error);await prisma.$disconnect();process.exit(1)});
