import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { CampaignChannel, CampaignStatus, ContactStatus, ExecutionMode, Prisma, RecipientStatus } from '@prisma/client';
import * as bcrypt from 'bcrypt'; import { JwtService } from '@nestjs/jwt'; import { InjectQueue } from '@nestjs/bullmq'; import { Queue } from 'bullmq';
import { AuditService } from './audit.service'; import { PrismaService } from './prisma.service'; import { CampaignDto, ContactDto, CreateUserDto, SegmentDto, SettingsDto, UpdateUserDto } from './dto';
import { MfaService } from './mfa.service';
const publicUser = { passwordHash: false } as const;
@Injectable()
export class AppService {
 constructor(private prisma: PrismaService, private jwt: JwtService, private audit: AuditService, private mfa: MfaService, @InjectQueue('campaigns') private queue: Queue) {}
 async login(email: string, password: string) { const user = await this.prisma.user.findUnique({ where: { email: email.toLowerCase() } }); if (!user || !user.isActive || !(await bcrypt.compare(password, user.passwordHash))) throw new BadRequestException('Credenciales inválidas o cuenta inactiva'); const settings = await this.settings(); if (user.mfaEnabled || settings.mfaEnforced) return { mfaRequired: true, mfaSetupRequired: !user.mfaEnabled, mfaToken: await this.mfaToken(user) }; return this.completeLogin(user.id); }
 private async mfaToken(user: { id:string; email:string; role:unknown }) { return this.jwt.signAsync({ sub:user.id, email:user.email, role:user.role, mfaChallenge:true }, { expiresIn:'5m' }); }
 private async completeLogin(userId: string) { const user = await this.prisma.user.update({ where: { id: userId }, data: { lastLoginAt: new Date() } }); await this.audit.log(user.id, 'LOGIN', 'User', user.id); const accessToken = await this.jwt.signAsync({ sub: user.id, email: user.email, role: user.role }); return { accessToken, user: this.userDto(user) }; }
 private async challengeUser(mfaToken: string) { try { const payload = await this.jwt.verifyAsync(mfaToken); if (!payload.mfaChallenge || !payload.sub) throw new Error(); const user = await this.prisma.user.findUnique({ where: { id: payload.sub } }); if (!user || !user.isActive) throw new Error(); return user; } catch { throw new BadRequestException('El reto MFA es inválido o expiró'); } }
 async setupMfa(mfaToken: string) { const user = await this.challengeUser(mfaToken); const secret = this.mfa.generateSecret(); await this.prisma.user.update({ where:{id:user.id}, data:{mfaSecret:this.mfa.encrypt(secret),mfaEnabled:false} }); await this.audit.log(user.id,'MFA_SETUP_STARTED','User',user.id); return { secret, otpauthUri:this.mfa.otpauthUri(user.email,secret), periodSeconds:30 }; }
 async activateMfa(mfaToken:string, code:string) { const user=await this.challengeUser(mfaToken); if(!user.mfaSecret || !(await this.mfa.verify(this.mfa.decrypt(user.mfaSecret),code))) throw new BadRequestException('Código MFA inválido o vencido'); await this.prisma.user.update({where:{id:user.id},data:{mfaEnabled:true}}); await this.audit.log(user.id,'MFA_ENABLED','User',user.id); return this.completeLogin(user.id); }
 async verifyMfa(mfaToken:string, code:string) { const user=await this.challengeUser(mfaToken); if(!user.mfaEnabled || !user.mfaSecret || !(await this.mfa.verify(this.mfa.decrypt(user.mfaSecret),code))) throw new BadRequestException('Código MFA inválido o vencido'); return this.completeLogin(user.id); }
 userDto(user: { id:string; name:string; email:string; role: unknown; isActive:boolean; mfaEnabled:boolean; lastLoginAt:Date|null; createdAt:Date }) { return { id:user.id, name:user.name, email:user.email, role:user.role, isActive:user.isActive, mfaEnabled:user.mfaEnabled, lastLoginAt:user.lastLoginAt, createdAt:user.createdAt }; }
 async me(id: string) { const user = await this.prisma.user.findUnique({ where: { id } }); if (!user) throw new NotFoundException('Usuario no encontrado'); return this.userDto(user); }
 async users() { return (await this.prisma.user.findMany({ orderBy:{createdAt:'desc'} })).map(u => this.userDto(u)); }
 async createUser(dto: CreateUserDto, actor: string) { const { password, ...data } = dto; const user = await this.prisma.user.create({ data: { ...data, email: data.email.toLowerCase(), passwordHash: await bcrypt.hash(password, 12) } }); await this.audit.log(actor, 'CREATE_USER', 'User', user.id); return this.userDto(user); }
 async updateUser(id:string,dto:UpdateUserDto,actor:string) { const user=await this.prisma.user.update({where:{id},data:{...dto,email:dto.email?.toLowerCase()}}); await this.audit.log(actor,'UPDATE_USER','User',id); return this.userDto(user); }
 async userStatus(id:string,isActive:boolean,actor:string) { if (id===actor && !isActive) throw new BadRequestException('No puede desactivar su propia cuenta'); const user=await this.prisma.user.update({where:{id},data:{isActive}}); await this.audit.log(actor,'UPDATE_USER_STATUS','User',id,{isActive}); return this.userDto(user); }
 async resetUserMfa(id:string,actor:string) { const user=await this.prisma.user.update({where:{id},data:{mfaEnabled:false,mfaSecret:null}}); await this.audit.log(actor,'MFA_RESET','User',id); return this.userDto(user); }
 contactWhere(query: Record<string, string>) { const where: Prisma.ContactWhereInput = {}; if(query.search) where.OR=[{firstName:{contains:query.search,mode:'insensitive'}},{lastName:{contains:query.search,mode:'insensitive'}},{phone:{contains:query.search}}]; if(query.status) where.status=query.status as ContactStatus; if(query.zone) where.zone={contains:query.zone,mode:'insensitive'}; if(query.group) where.groupName={contains:query.group,mode:'insensitive'}; if(query.whatsappOptIn) where.whatsappOptIn=query.whatsappOptIn==='true'; if(query.smsOptIn) where.smsOptIn=query.smsOptIn==='true'; return where; }
 async contacts(query: Record<string,string>) { const page=Math.max(1,Number(query.page||1)), limit=Math.min(100,Math.max(1,Number(query.limit||25))); const where=this.contactWhere(query); const [data,total]=await this.prisma.$transaction([this.prisma.contact.findMany({where,skip:(page-1)*limit,take:limit,orderBy:{createdAt:'desc'}}),this.prisma.contact.count({where})]); return {data,meta:{page,limit,total,totalPages:Math.ceil(total/limit)}}; }
 async contact(id:string) { const contact=await this.prisma.contact.findUnique({where:{id}}); if(!contact) throw new NotFoundException('Contacto no encontrado'); return contact; }
 contactData(dto:ContactDto) {
  const legacy = (dto.departmentOrZone || '').split(' / ').map(value => value.trim()).filter(Boolean);
  const { departmentOrZone: _legacy, ...contact } = dto;
  return {...contact, phone:dto.phone.replace(/\s/g,''), department:dto.department?.trim() || legacy[0] || null, zone:dto.zone?.trim() || legacy[1] || (legacy.length === 1 ? legacy[0] : null), consentAt:(dto.whatsappOptIn || dto.smsOptIn) ? new Date(): undefined};
 }
 async createContact(dto:ContactDto,actor:string) { const contact=await this.prisma.contact.create({data:this.contactData(dto)}); await this.audit.log(actor,'CREATE_CONTACT','Contact',contact.id); return contact; }
 async updateContact(id:string,dto:Partial<ContactDto>,actor:string) { const contact=await this.prisma.contact.update({where:{id},data:this.contactData(dto as ContactDto)}); await this.audit.log(actor,'UPDATE_CONTACT','Contact',id); return contact; }
 async deleteContact(id:string,actor:string) { const contact=await this.prisma.contact.findUnique({where:{id},include:{_count:{select:{recipients:true}}}}); if(!contact) throw new NotFoundException('Contacto no encontrado'); if(contact._count.recipients) throw new BadRequestException('El contacto tiene historial de campañas; use dar de baja para conservar la trazabilidad'); await this.prisma.contact.delete({where:{id}}); await this.audit.log(actor,'DELETE_CONTACT','Contact',id); return {success:true}; }
 async contactStatus(id:string,status:ContactStatus,actor:string) { const contact=await this.prisma.contact.update({where:{id},data:{status}}); await this.audit.log(actor,status===ContactStatus.INACTIVE?'DEACTIVATE_CONTACT':'UPDATE_CONTACT_STATUS','Contact',id,{status}); return contact; }
 async optOut(id:string,actor:string) { const contact=await this.prisma.contact.update({where:{id},data:{optOutAt:new Date(),whatsappOptIn:false,smsOptIn:false,status:ContactStatus.INACTIVE}}); await this.audit.log(actor,'OPT_OUT_CONTACT','Contact',id); return contact; }
 async importContacts(rows: ContactDto[],actor:string) { let imported=0, failed=0; for(const row of rows) { try { await this.prisma.contact.upsert({where:{phone:row.phone.replace(/\s/g,'')},create:this.contactData(row),update:this.contactData(row)}); imported++; } catch { failed++; } } await this.audit.log(actor,'IMPORT_CONTACTS','Contact','bulk',{imported,failed}); return {imported,failed}; }
 async segments() { return this.prisma.segment.findMany({include:{createdBy:{select:{id:true,name:true,email:true}}},orderBy:{createdAt:'desc'}}); }
 async segment(id:string) { const item=await this.prisma.segment.findUnique({where:{id}}); if(!item) throw new NotFoundException('Segmento no encontrado'); return item; }
 async createSegment(dto:SegmentDto,actor:string) { const item=await this.prisma.segment.create({data:{...dto,filters:dto.filters as Prisma.InputJsonValue,createdById:actor}}); await this.audit.log(actor,'CREATE_SEGMENT','Segment',item.id); return item; }
 async updateSegment(id:string,dto:Partial<SegmentDto>,actor:string) { const item=await this.prisma.segment.update({where:{id},data:{...dto,filters:dto.filters as Prisma.InputJsonValue}}); await this.audit.log(actor,'UPDATE_SEGMENT','Segment',id); return item; }
 async deleteSegment(id:string,actor:string) { await this.prisma.segment.delete({where:{id}}); await this.audit.log(actor,'DELETE_SEGMENT','Segment',id); return {success:true}; }
 async segmentContacts(id:string) { const segment=await this.segment(id); return this.eligibleContacts(segment.filters as Record<string,unknown>,undefined,false); }
 async eligibleContacts(filters:Record<string,unknown>, channel?:CampaignChannel, twilioOnly=false) { const where: Prisma.ContactWhereInput={status:ContactStatus.ACTIVE,optOutAt:null}; if(filters.zone) where.zone={equals:String(filters.zone),mode:'insensitive'}; if(filters.group) where.groupName={contains:String(filters.group),mode:'insensitive'}; if(filters.whatsappOptIn) where.whatsappOptIn=true; if(filters.smsOptIn) where.smsOptIn=true; if(filters.isTwilioTestNumber || twilioOnly) where.isTwilioTestNumber=true; if(channel===CampaignChannel.WHATSAPP) where.whatsappOptIn=true; if(channel===CampaignChannel.SMS) where.smsOptIn=true; if(channel===CampaignChannel.BOTH) where.OR=[{whatsappOptIn:true},{smsOptIn:true}]; return this.prisma.contact.findMany({where}); }
 async createCampaign(dto:CampaignDto,actor:string) { if(dto.executionMode===ExecutionMode.META_TEST&&dto.channel!==CampaignChannel.WHATSAPP) throw new BadRequestException('Meta WhatsApp de prueba solo permite el canal WhatsApp'); const filters:Record<string,unknown> = dto.segmentId ? (await this.segment(dto.segmentId)).filters as Record<string,unknown> : {}; const testOnly=dto.executionMode===ExecutionMode.TWILIO_TEST||dto.executionMode===ExecutionMode.META_TEST; const contacts=dto.contactIds!==undefined ? await this.prisma.contact.findMany({where:{id:{in:dto.contactIds}}}) : dto.segmentId ? await this.eligibleContacts(filters,dto.channel,testOnly) : []; const eligible=contacts.filter(c=>c.status===ContactStatus.ACTIVE&&!c.optOutAt&&(!testOnly||c.isTwilioTestNumber)&&(dto.channel===CampaignChannel.BOTH ? c.whatsappOptIn||c.smsOptIn : dto.channel===CampaignChannel.WHATSAPP ? c.whatsappOptIn : c.smsOptIn)); const rate=await this.settings(); const unit=dto.channel===CampaignChannel.SMS?Number(rate.smsRatePerThousand)/1000:Number(rate.whatsappUtilityRatePerThousand)/1000; const campaign=await this.prisma.campaign.create({data:{...dto,contactIds:dto.contactIds as Prisma.InputJsonValue|undefined,variables:dto.variables as Prisma.InputJsonValue,scheduledAt:dto.scheduledAt?new Date(dto.scheduledAt):undefined,status:dto.scheduledAt?CampaignStatus.SCHEDULED:CampaignStatus.DRAFT,createdById:actor,estimatedRecipients:eligible.length,estimatedCost:eligible.length*unit}}); await this.audit.log(actor,'CREATE_CAMPAIGN','Campaign',campaign.id,{eligibleRecipients:eligible.length}); return campaign; }
 async campaigns() { return this.prisma.campaign.findMany({include:{segment:true,createdBy:{select:{id:true,name:true,email:true}},_count:{select:{recipients:true}}},orderBy:{createdAt:'desc'}}); }
 async campaign(id:string) { const item=await this.prisma.campaign.findUnique({where:{id},include:{segment:true,createdBy:{select:{id:true,name:true,email:true}}}}); if(!item) throw new NotFoundException('Campaña no encontrada'); return item; }
 async updateCampaign(id:string,dto:Partial<CampaignDto>,actor:string) { const item=await this.prisma.campaign.update({where:{id},data:{...dto,variables:dto.variables as Prisma.InputJsonValue,scheduledAt:dto.scheduledAt?new Date(dto.scheduledAt):undefined}}); await this.audit.log(actor,'UPDATE_CAMPAIGN','Campaign',id); return item; }
 async previewCampaign(id:string) { const c=await this.campaign(id); const testOnly=c.executionMode===ExecutionMode.TWILIO_TEST||c.executionMode===ExecutionMode.META_TEST; const filters=c.segment ? c.segment.filters as Record<string,unknown> : {}; const selectedIds=Array.isArray(c.contactIds)?c.contactIds.filter((id):id is string=>typeof id==='string'):[]; const contacts=c.contactIds!==null ? await this.prisma.contact.findMany({where:{id:{in:selectedIds}}}) : c.segment ? await this.eligibleContacts(filters,c.channel,testOnly) : []; const eligible=contacts.filter(x=>x.status===ContactStatus.ACTIVE&&!x.optOutAt&&(!testOnly||x.isTwilioTestNumber)&&(c.channel===CampaignChannel.BOTH?x.whatsappOptIn||x.smsOptIn:c.channel===CampaignChannel.WHATSAPP?x.whatsappOptIn:x.smsOptIn)); return {campaignId:id,executionMode:c.executionMode,isSimulation:c.executionMode===ExecutionMode.DEMO,eligibleRecipients:eligible.length,sample:eligible.slice(0,5).map(x=>({contact:x,renderedMessage:this.render(c.message,x)}))}; }
 render(message:string, contact:{firstName:string;lastName:string;phone:string}) { return message.replace(/{{\s*nombre\s*}}/gi,contact.firstName).replace(/{{\s*apellido\s*}}/gi,contact.lastName).replace(/{{\s*telefono\s*}}/gi,contact.phone); }
 async sendCampaign(id:string,actor:string) { const c=await this.campaign(id); if(c.executionMode===ExecutionMode.LIVE) throw new BadRequestException('El modo LIVE requiere configurar y aprobar el proveedor de mensajería'); if(c.status===CampaignStatus.CANCELLED) throw new BadRequestException('La campaña está cancelada'); if(c.estimatedRecipients<1) throw new BadRequestException('La campaña no tiene destinatarios elegibles; revise consentimiento, autorización de prueba y segmento'); if(c.executionMode===ExecutionMode.META_TEST&&(!process.env.META_WA_ACCESS_TOKEN||!process.env.META_WA_PHONE_NUMBER_ID)) throw new BadRequestException('Configure META_WA_ACCESS_TOKEN y META_WA_PHONE_NUMBER_ID en backend/.env antes de enviar'); await this.prisma.campaign.update({where:{id},data:{status:CampaignStatus.PROCESSING}}); await this.queue.add('process',{campaignId:id},{removeOnComplete:100,removeOnFail:100}); await this.audit.log(actor,'SEND_CAMPAIGN','Campaign',id,{executionMode:c.executionMode}); return {campaignId:id,status:CampaignStatus.PROCESSING,message:c.executionMode===ExecutionMode.DEMO?'Simulación encolada; no se enviarán mensajes reales.':'Envío de prueba encolado'}; }
 async cancelCampaign(id:string,actor:string) { const c=await this.prisma.campaign.update({where:{id},data:{status:CampaignStatus.CANCELLED}}); await this.prisma.campaignRecipient.updateMany({where:{campaignId:id,status:{in:[RecipientStatus.PENDING,RecipientStatus.QUEUED]}},data:{status:RecipientStatus.CANCELLED}}); await this.audit.log(actor,'CANCEL_CAMPAIGN','Campaign',id); return c; }
 async recipients(id:string, query:Record<string,string>) { const page=Math.max(1,Number(query.page||1)),limit=Math.min(100,Number(query.limit||25)); const where={campaignId:id}; const [data,total]=await this.prisma.$transaction([this.prisma.campaignRecipient.findMany({where,include:{contact:true},skip:(page-1)*limit,take:limit,orderBy:{createdAt:'desc'}}),this.prisma.campaignRecipient.count({where})]); return {data,meta:{page,limit,total}}; }
 async processMetaWebhook(body: any) { const updates = (body?.entry || []).flatMap((entry: any) => entry.changes || []).flatMap((change: any) => change.value?.statuses || []); for (const update of updates) { if (!update.id) continue; const status = update.status === 'delivered' ? RecipientStatus.DELIVERED : update.status === 'read' ? RecipientStatus.READ : update.status === 'failed' ? RecipientStatus.FAILED : update.status === 'sent' ? RecipientStatus.SENT : undefined; if (!status) continue; const at = update.timestamp ? new Date(Number(update.timestamp) * 1000) : new Date(); await this.prisma.campaignRecipient.updateMany({ where: { providerMessageId: update.id }, data: { status, ...(status === RecipientStatus.DELIVERED ? { deliveredAt: at } : {}), ...(status === RecipientStatus.READ ? { deliveredAt: at, readAt: at } : {}), ...(status === RecipientStatus.FAILED ? { errorMessage: update.errors?.[0]?.title || update.errors?.[0]?.message || 'Meta reportó un fallo de entrega' } : {}) } }); } return { received: true }; }
 async report(id:string) { const statuses=await this.prisma.campaignRecipient.groupBy({by:['status'],where:{campaignId:id},_count:true}); return {campaign:await this.campaign(id),statuses:Object.fromEntries(statuses.map(x=>[x.status,x._count]))}; }
 async messages(query:Record<string,string>) { const where:Prisma.CampaignRecipientWhereInput={}; if(query.campaignId) where.campaignId=query.campaignId; return this.prisma.campaignRecipient.findMany({where,include:{contact:true,campaign:true},orderBy:{createdAt:'desc'},take:Math.min(200,Number(query.limit||100))}); }
 async reports() { const campaigns=await this.prisma.campaign.findMany({include:{_count:{select:{recipients:true}}},orderBy:{createdAt:'desc'}}); return campaigns; }
 async settings() { return await this.prisma.appSetting.findFirst() ?? {organizationName:'',supportEmail:null,supportPhone:null,allowedStartHour:8,allowedEndHour:20,whatsappUtilityRatePerThousand:0,whatsappMarketingRatePerThousand:0,smsRatePerThousand:0,mfaEnforced:false}; }
 async branding() { const setting=await this.prisma.appSetting.findFirst({select:{logoDataUrl:true}}); return {logoDataUrl:setting?.logoDataUrl ?? null}; }
 async updateSettings(dto:SettingsDto,actor:string) { const old=await this.prisma.appSetting.findFirst(); const item=old ? await this.prisma.appSetting.update({where:{id:old.id},data:dto}) : await this.prisma.appSetting.create({data:{organizationName:dto.organizationName||'Conecta Masivo',...dto}}); await this.audit.log(actor,'UPDATE_SETTINGS','AppSetting',item.id); return item; }
 async updateMfaEnforcement(mfaEnforced:boolean,actor:string) { const old=await this.prisma.appSetting.findFirst(); const item=old ? await this.prisma.appSetting.update({where:{id:old.id},data:{mfaEnforced}}) : await this.prisma.appSetting.create({data:{organizationName:'Conecta Masivo',mfaEnforced}}); await this.audit.log(actor,'MFA_ENFORCEMENT_CHANGED','AppSetting',item.id,{mfaEnforced}); return {mfaEnforced:item.mfaEnforced}; }
 async dashboard() { const start=new Date(); start.setDate(1); const [contacts,whatsapp,sms,campaigns,recent,statuses]=await this.prisma.$transaction([this.prisma.contact.count(),this.prisma.contact.count({where:{whatsappOptIn:true,optOutAt:null,status:ContactStatus.ACTIVE}}),this.prisma.contact.count({where:{smsOptIn:true,optOutAt:null,status:ContactStatus.ACTIVE}}),this.prisma.campaign.count({where:{createdAt:{gte:start}}}),this.prisma.campaign.findMany({take:5,orderBy:{createdAt:'desc'}}),this.prisma.campaignRecipient.groupBy({by:['status'],_count:true,orderBy:{status:'asc'}})]); return {contacts:{total:contacts,whatsappOptIn:whatsapp,smsOptIn:sms},campaignsThisMonth:campaigns,messagesByStatus:Object.fromEntries(statuses.map(x=>[x.status,x._count])),recentCampaigns:recent}; }
 async auditLogs() { return this.prisma.auditLog.findMany({include:{user:{select:{name:true,email:true,role:true}}},orderBy:{createdAt:'desc'},take:200}); }
}
