ALTER TABLE "User" ADD COLUMN "mfaEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN "mfaSecret" TEXT;
ALTER TABLE "AppSetting" ADD COLUMN "mfaEnforced" BOOLEAN NOT NULL DEFAULT false;
